### ISSUE TITLE
Annotations display on top of YouTube Ads

### ISSUE THREAD

**Issue by tech234a** [afrmtbl/AnnotationsRestored#17]
Annotations display on top of YouTube ads if annotations exist at that paused point in the video. The timer does not appear to continue to run. Note that annotations do not display on top of "call to action" screens following ads (static screens in the video player with a logo, a button, and some text).

**Comment by afrmtbl** [comment]
Annotations are now hidden when ads are playing (b78e0f8ea84656b09dd128c24e2c574c588ac9a3)
