### ISSUE TITLE
Links broken in some "choose your adventure" videos

### ISSUE THREAD

**Issue by TheOldOne822** [afrmtbl/AnnotationsRestored#26]
Here is an example https://www.youtube.com/watch?v=PWYY4BCAyzQ

Links to points within video work but not to other videos

**Comment by afrmtbl** [comment]
@TheOldOne822 Do you mind trying it out again? 
It should be working now (tested on Chrome 77 and Firefox 69)

**Comment by TheOldOne822** [comment]
It is working now
