### ISSUE TITLE
Document the format needed for new annotations

### ISSUE THREAD

**Issue by tech234a** [afrmtbl/AnnotationsRestored#3]
A short document explaining the format for new annotations would be nice so people can start experimenting with making their own new annotations (or someone could implement an annotation creator).

**Comment by tech234a** [comment]
Is ```tp``` (type) always ```text```? Or is it just in the sample file I have? What are the possible values for ```tp```?

**Comment by tech234a** [comment]
Is the ```style``` attribute planned to be supported? (I know this is an early-stage project, I'm just curious how much will be preserved.)

**Comment by tech234a** [comment]
One more thing- I'd also like to point out a resource that is helping me visualize the YouTube annotations format, and it may help others too: http://xmlgrid.net makes it easier to see all of the properties associated with each annotation.
(Sorry for all of the comments.)

**Comment by afrmtbl** [comment]
Also created a [wiki](https://github.com/afrmtbl/AnnotationsRestored/wiki/YouTube-annotation-attributes) to go along with the [format documentation](https://github.com/afrmtbl/AnnotationsRestored/commit/8a0618cbc0054864cdcc96efb8d7ec3f60f3d26a)
