### ISSUE TITLE
Hover text doesn't appear

### ISSUE THREAD

**Issue by yaboykevin01** [afrmtbl/AnnotationsRestored#33]
Annotation text that should appear when moused over (i.e. "condition state=rollOver" in the unconverted YouTube data) does not appear.
Examples:
 [Super Luigi Galaxy - Episode 1](https://youtu.be/9olvSnGn9sg?list=PLCE45619ABCC32396&t=188).
The two small boxes in the lower corners at this timestamp should have hover text that reads "Back to Comet Observatory" and "Back to Gateway Galaxy Mission Select," respectively. However, that text isn't appearing for me.
[Super Mario Sunshine - Gelato Beach Menu](https://www.youtube.com/watch?v=E0t5u78YkNI).
The annotation in the lower right should have hover text that reads "Blue Coins," the second annotation of a mission should have hover text that reads "Bonus Shine," etc.
[Super Luigi Galaxy - Comet Observatory Menu](https://www.youtube.com/watch?v=MlztVaIStuM).
Almost every annotation on the screen should have hover text that indicates to which galaxy the corresponding annotation will take the viewer. The absence of hover text renders this interactive menu system almost unusable.

I found these issues while using the latest version of Firefox (70.0).

**Comment by afrmtbl** [comment]
@yaboykevin01 `highlightText` annotations are now supported as of v0.7 of the extension.
https://github.com/afrmtbl/annotationlib/commit/665b3d959de94805aa612b6b19215531e77f52bd
There are still a few inaccuracies regarding text size tracked in https://github.com/afrmtbl/annotationlib/issues/11

Thanks for reporting this :slightly_smiling_face:

**Comment by yaboykevin01** [comment]
I just downloaded the newest version of the extension and tried again, and it's working like a charm. Thank you for all the work you're doing on this. I'm glad annotations can still be made to work like they originally did.
