### ISSUE TITLE
Remove "Read your browser history" permission

### ISSUE THREAD

**Issue by ajayyy** [afrmtbl/AnnotationsRestored#34]
This is not an urgent thing, just something to think about to make the permissions a little less scary.

Basically, instead of checking the URL in the background script, you send the content script a message and have the content script check it's url.

You can see the kind of changes required in this changes from this PR: https://github.com/ajayyy/SponsorBlock/pull/90

> You can use most chrome.tabs methods and events without declaring any permissions in the extension's manifest file. However, if you require access to the url, pendingUrl, title, or favIconUrl properties of tabs.Tab, you must declare the "tabs" permission in the manifest

Source: https://developer.chrome.com/extensions/tabs

**Comment by afrmtbl** [comment]
Tabs permission removed in 1a36a01b888141dfd0c9e0fded6ab8396dbfd676
Thanks for the idea!
