### ISSUE TITLE
Annotations Do Not Appear In Old or New Youtube

### ISSUE THREAD

**Issue by Luigimeansme** [afrmtbl/AnnotationsRestored#37]
I downloaded this extension and after reading the description, I thought it would get the annotations automatically. However, unless I did something wrong, I cannot get annotations to appear. I have tried videos like the Annotation Tetris video, the Chuggaaconroy Mario 64 DS video shown in the Google Web Store page for this app, and Chuggaaconroy's entire Kid Icarus Uprising series to no avail. Please let me know if I am doing something wrong or not, thank you!

**Comment by afrmtbl** [comment]
Yeah, there's currently a few problems with how the current video playing is detected. I'll be releasing an update that addresses this sometime in the next few days :)

For now you can try refreshing once when you get to a video's page.

**Comment by Luigimeansme** [comment]
Any news on the update yet? I'm sorry if I seem impatient, but there's a few things I want to go back and watch that just aren't the same without annotations

**Comment by afrmtbl** [comment]
No problem at all :)

I've actually already released the update but it's been rejected twice now on the Chrome Web Store. It's up on the Mozilla one though if you use Firefox.

If you use Chrome you can download and install the latest version of the extension manually by following the `Install from source` instructions [here](https://github.com/afrmtbl/AnnotationsRestored#installation).

Hope this helps!

**Comment by Luigimeansme** [comment]
Looks like it's working great so far! Thank you so much!
