### ISSUE TITLE
Allow YouTube Playlist Links

### ISSUE THREAD

**Issue by tech234a** [afrmtbl/AnnotationsRestored#8]
URL filtering currently blocks links to YouTube playlists.

Example video: https://www.youtube.com/watch?v=eIRvFqyPfos at 1:26

Annotation Code:
`<annotation id="annotation_165304265" type="highlight" log_data="a-v=eIRvFqyPfos&l-class=2&link=http%3A%2F%2Fwww.youtube.com%2Fplaylist%3Flist%3DPLD0871DD999F067E6&xble=1&a-id=annotation_165304265&a-type=3&ei=KzMkXMqhGJqEz7sPj7KvGA" itct="CAUQs-UBGP___________wEiEwiK46Pu9b7fAhUawnMBHQ_ZCwMo-B0yAml2SIv9veTq4pvCeA">
<segment>
<movingRegion type="rect">
<rectRegion x="36.92600" y="7.32400" w="27.69400" h="20.73200" t="3:16.000"/>
<rectRegion x="36.92600" y="7.32400" w="27.69400" h="20.73200" t="3:18.500"/>
</movingRegion>
</segment>
<appearance bgColor="15395562" highlightWidth="3" borderAlpha="0.2"/>
<action type="openUrl" trigger="click">
<url target="current" value="https://www.youtube.com/playlist?annotation_id=annotation_165304265&ei=KzMkXMqhGJqEz7sPj7KvGA&feature=iv&list=PLD0871DD999F067E6&src_vid=eIRvFqyPfos" link_class="2"/>
</action>
</annotation>`

**Comment by tech234a** [comment]
It seems that these links are removed from the annotations during the conversion process.

**Comment by afrmtbl** [comment]
Looks like any links that aren't to videos are being stripped: #9

**Comment by afrmtbl** [comment]
Fixed with ac729f932becdc0f621fbaa658dd2dcee37bbc9b
